### ISSUE TITLE
Tooltips for Book Web (Review this issue on a later stage)

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#1]
The tooltips displayed on the Book Web on relevant interactions (see [Req. 2.9](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.be25ggj1naoy) and [req. 7.4](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.1uttnsjpemdi)).

**Comment by jeongoks** [comment]
Closing this because we scrapped this feature due to time-limit.
