### ISSUE TITLE
Implement Polly

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#10]
[See Req. 4.11](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.963roe3wcdg1)

**Comment by Sjimooon** [comment]
I have done a flexible implementation of Polly retries before. I'll see if I can dig that up and see if we can use that.
