### ISSUE TITLE
Update BooksController AddBook

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#102]
Currently the `BooksController` takes in a `Guid[]` On both the `Genres` and `Authors` We need to be able to send a string in for their name/title, otherwise a publisher isn't able to add these when creating a new book.

**Comment by jeongoks** [comment]
So in the ui we will call the `GenreCreateModel` For each genre there needs to be added, get their `Guids` and send down to the `BookCreateModel` when creating the book, same with `Authors`? 🤔

**Comment by Sjimooon** [comment]
I think the way you describe it would be the way to do it. We just do many but smaller and simpler requests.
