### ISSUE TITLE
Add Serilog

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#107]
Add Serilog to the API project.

**Comment by Sjimooon** [comment]
Serilog has been configered so that we can write logs with it using the `ILogger<T>`.
Only a few things are being logged at the moment. What should I add more logging to? I think in all places where we'll throw exeptions and/or end up with a HTTP 500 response, but what else? 🤔

**Comment by ZhakalenDk** [comment]
I agree. Everytime we encounter some change in flow we should log it.
I'd also like it if we can track operations done by either users, publishers and operators

**Comment by Sjimooon** [comment]
After a talk, we decided to wait with additional logging and created #128.
