### ISSUE TITLE
Pull data for visualization tools

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#11]
[See Req. 4.12 and sub-requirements](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.8vqhmmif8yeg)

**Comment by ZhakalenDk** [comment]
THis is closed because the feature was scrapped
