### ISSUE TITLE
Handle terminated publisher's content

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#12]
The way that the publisher's content will be handle if they're terminated.

[See Req. 4.13](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.swborsotkjkw)

**Comment by ZhakalenDk** [comment]
This is closed because the feature is implemented, however, it has not been tested and is waiting for #157 
. CLosing it.
