### ISSUE TITLE
Library search on Mobile

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#122]
The library and the search functionality

**Comment by ZhakalenDk** [comment]
![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/ce883e2a-44b3-4209-933d-39c0a15fee93)

**Comment by ZhakalenDk** [comment]
![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/a1abaad6-2025-4313-8e9d-cb8bddde27e8)

**Comment by ZhakalenDk** [comment]
![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/7ecd29de-93e0-41ca-83e4-cc4f43dc1849)



![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/a7715727-a4ea-485a-a828-3efa2a8babd9)

**Comment by jeongoks** [comment]
UI genius? 😲
