### ISSUE TITLE
Handle encryption on communication

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#14]
[See Req. 4.15](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.8y4hy7v5bdo5) and [See Req. 6.8](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.ujm7l5jc9l4j)

**Comment by ZhakalenDk** [comment]
>Implementing HSTS: A simple one-liner
>The trivial man-in-the-middle attacks described above can be thwarted by implementing an appropriate HSTS policy. A secure >website can do this simply by setting a single HTTP header in its responses:
>`Strict-Transport-Security: max-age=31536000;`
>This header can only be set over an HTTPS connection, and instructs compatible browsers to only access the site over HTTPS for the next year (31,536,000 seconds = 1 year). This is the most common max-age value, used by nearly half of all HTTPS servers. After this HSTS policy has been applied, even if a user manually prefixes the site’s hostname with http://, the browser will ignore this and access the site over HTTPS instead.


[Source](https://www.netcraft.com/blog/95-of-https-servers-vulnerable-to-trivial-mitm-attacks/#:~:text=Even%20if%20a%20secure%20website,middle%20attacks%20are%20still%20possible.)

**Comment by jeongoks** [comment]
[Source](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&viewFallbackFrom=aspnetcore-2.1&tabs=visual-studio%2Clinux-ubuntu#http-strict-transport-security-protocol-hsts)
