### ISSUE TITLE
ToQuery not processing collections correctly

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#143]
However takes this just replace the code in `GenericExtensions` -> `ToQuery<TObject>` with this code:

```cs
        /// <summary>
        /// Converts this <typeparamref name="TObject"/> into a query representation of itself
        /// </summary>
        /// <typeparam name="TObject"></typeparam>
        /// <param name="obj"></param>
        /// <param name="ignoreNull">Whether or not <see langword="null"/> values should be excluded from the query <see langword="string"/></param>
        /// <param name="enforceLowercase">Whether or not property names should be formatted as <strong>lowercase</strong> characters</param>
        /// <returns>A <see langword="string"/> that represents <paramref name="obj"/> as query parameters</returns>
        public static string ToQuery<TObject>(this TObject obj, bool ignoreNull = false, bool enforceLowercase = false) where TObject : new()
        {
            string queryString = string.Empty;
            var properties = typeof(TObject).GetProperties();
            for (int i = 0; i < properties.Length; i++)
            {
                var propertyName = ((enforceLowercase) ? (properties[i].Name.ToLowerInvariant()) : (properties[i].Name));
                var propertyValue = properties[i].GetValue(obj);

                if (ignoreNull && propertyValue == null)
                    continue;

                if (propertyValue!.GetType().IsArray)
                {
                    var propertValueAsCollection = propertyValue as IList;
                    for (int j = 0; j < propertValueAsCollection!.Count; j++)
                    {
                        queryString += $"{propertyName}={propertValueAsCollection[j]?.ToString()}{(((j + 1 < propertValueAsCollection.Count) || i + 1 < properties.Length) ? ("&") : (string.Empty))}";
                    }

                    continue;
                }

                queryString += $"{propertyName}={propertyValue}{((i + 1 < properties.Length) ? ("&") : (string.Empty))}";
            }

            return queryString;
        }
```

This lets the method process arrays.

**Comment by Sjimooon** [comment]
Shouldn't we set the `ignoreNull` parameter to `true` by default, so that we won't try to convert properties with a value of `null` to query parameters? An query parameter with an empty value wouldn't be of much use 😅

![image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/122673993/0516693e-265c-4ba3-b9ab-50ac96112bd7)

**Comment by ZhakalenDk** [comment]
> Shouldn't we set the `ignoreNull` parameter to `true` by default, so that we won't try to convert properties with a value of `null` to query parameters? I don't think a query parameter with an empty value wouldn't be of much use 😅
> 
> ![image](https://private-user-images.githubusercontent.com/122673993/320014532-0516693e-265c-4ba3-b9ab-50ac96112bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjc2ODMsIm5iZiI6MTcxMjMyNzM4MywicGF0aCI6Ii8xMjI2NzM5OTMvMzIwMDE0NTMyLTA1MTY2OTNlLTI2NWMtNGJhMy1iOWFiLTUwYWM5NjExMmJkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNDI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjk2ZDg4ZmIwY2E3MDQ1MGUzYTY3OTRhMzU1NzNmNmNmNjcxNTQzY2YzODczNzA2NWNlNzM0NWNjNGY1OWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tKERLjvMgNy6oP1VuVTez1Rxh04IVYXD16FQYMA3M8E)

I get your point. However, the value null is still a value 🤔 

We could however check if the type is colelctiojn and mainly state if that is null or empty simply leave it out 🤷
