### ISSUE TITLE
Search page (Book Web)

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#16]
Should be equivalant to [See Req. 4.17.b](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.fmz2mrsnjnr4)

**Comment by ZhakalenDk** [comment]
@jeongoks Can you give this a priority and size?🤔
And also slap a label on it?

**Comment by jeongoks** [comment]
This is also closed, as we scrapped the Book Web.
