### ISSUE TITLE
Handle larger files

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#184]
Part of the Figure out Book content - taking this into a new issue so that we can divide the large issue in case it is needed - and we keep doing issues by feature and not by "epics".

**Comment by ZhakalenDk** [comment]
What do you mean with: `and we keep doing issues by feature and not by "epics"`.

That sounds like something based on Azure's Backlog view (:

**Comment by ZhakalenDk** [comment]
Well, there's nothing wrong in refering to some other ressource, however, I still don't know what you mean by it?

**Comment by jeongoks** [comment]
Just stating that I am taking one of the tasks in the #59 for now, so that I can keep them seperated, is all.

**Comment by ZhakalenDk** [comment]
We could store files on disk on the API server 🤷

**Comment by jeongoks** [comment]
We can try that, the error seems to happen when the client tries to upload so I think the client needs more but, we can talk about it today.

**Comment by jeongoks** [comment]
This link [here](https://github.com/App-vNext/Polly/issues/235) shows one way to come around it but, for now we want to focus on at least getting the e-books to show and then if there's time; change to store the actual file on the server and then have only the filePath in our SQL tables.
