### ISSUE TITLE
User Guides Admin Portal

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#2]

**Comment by jeongoks** [comment]
WIP. in case we manage to get the #184 to work.

[Here](https://docs.google.com/document/d/1JIOwrxjsx9DCOljGkFGCEh0aACGd-b8cA2RChUkc61I/edit#heading=h.a5g4krfhc9ke) is the user guide for now.

**Comment by jeongoks** [comment]
I have finished the initial of the user guide for the admin portal - any feedback or comments are appreciated!

You can access it [here](https://docs.google.com/document/d/1JIOwrxjsx9DCOljGkFGCEh0aACGd-b8cA2RChUkc61I/edit) and if you think it's sufficient, then close this issue. 😊
