### ISSUE TITLE
Rate Limiting on API

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#209]
The API needs to implement [rate limiting](https://blog.hubspot.com/website/api-rate-limit#:~:text=API%20rate%20limiting%20is%20a,what%20actions%20can%20be%20taken.) the amount of calls possible in sequence.

**Comment by jeongoks** [comment]
[Middleware](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0) documentation for ASP.NET if that can be used.

**Comment by jeongoks** [comment]
I will try to take a look at this but, I cannot promise i succeed. 😁
