### ISSUE TITLE
Third-party restrictions

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#22]
[See Req. 6.3.](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.qo26c4t3vkr)

**Comment by ZhakalenDk** [comment]
This is essentially done, however point: [Req. 6.3.a.ii](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.ctee17kcocm4) might not be.

Any thoughts, @jeongoks
