### ISSUE TITLE
Soft deletion

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#26]
See [req. 6.2.b](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.5h9vljpofcxi) (and maybe also [req. 6.2.a](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.65veyjs3ecsc)).

**Comment by ZhakalenDk** [comment]
This is implemented, isn't it?

**Comment by Sjimooon** [comment]
> This is implemented, isn't it?

Yes, accounts can be soft-deleted together with the associated operator or user and books can be hidden. All other data can only be _deleted_ deleted.
