### ISSUE TITLE
Alert Boxes (Book Mobile)

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#29]
[See Req. 4.2](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.v81q3o3smv6v) and [See Req. 7.2](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.76qc604wgilm)

**Comment by ZhakalenDk** [comment]
These do not show exactly what a user has to do to resolve the problem.
That doesn't make sense to implement, IMO 🤔 

Should we rewrite the requirements?

**Comment by jeongoks** [comment]
I normally write check values or something but, we can rewrite it for the book mobile as you do have alert boxes telling an error has occured - which is fine with me.
