### ISSUE TITLE
Visualization Tools for Admin Portal

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#3]
This issue is dependent on [this backlog issue](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/issues/11) being completed.

See: [Req. 4.1](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.1n9xt9anr8cc)

Should be equivalent to [See Req. 14.6.c](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.m2ldpymn9aj8)

**Comment by jeongoks** [comment]
https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.1n9xt9anr8cc

**Comment by ZhakalenDk** [comment]
CLosing because feature was scrapped
