### ISSUE TITLE
Tooltips for Book Mobile (Review this later)

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#30]
The tooltips displayed on the Book Web on relevant interactions (see [Req. 2.9](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.be25ggj1naoy) and [req. 7.4](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.1uttnsjpemdi)).

**Comment by ZhakalenDk** [comment]
Closing this as there's no place for these on book mobile
