### ISSUE TITLE
API endpoint table

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#31]
See [req. 8.3](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.jl8ahor47skm).

**Comment by jeongoks** [comment]
I've added the following api end point tables
 - [x] [User endpoint table](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Api-Documentation#user-endpoints).
 - [x] [Book endpoint table](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Api-Documentation#book-endpoints).
 - [x] [Publisher endpoint table](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Api-Documentation#publisher-endpoints).

We still need to do the following ones when their controllers gets done:
- [ ] Authentication endpoint table.
- [ ] Statistic endpoint table.

**Comment by ZhakalenDk** [comment]
Could we do something like [this](https://github.com/Mike-Mortensen-Portfolio/Oiski.School.THOP?tab=readme-ov-file#endpoints) for the endpoints table?

I think it would be good to have examples of both request and response bodies present. It will enhance the understanding and ease of use of our API.

**Comment by Sjimooon** [comment]
I agree with Mike, that would be nice 🙂

**Comment by jeongoks** [comment]
I thought those would be done for issue #37 or #33

**Comment by ZhakalenDk** [comment]
Aaah, Yes. That would make sense.
So what you've made here is just an overview?

**Comment by jeongoks** [comment]
Yes, we can also just combine those two but, I thought we agreed to an overview and then a more in-depth table for the sub-requirements in our requirement specification? I am fine with combining them. [Req. 8.3](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.jl8ahor47skm) The overview table will then become the entire 8.3.a sub-requirement if we combine them.

**Comment by ZhakalenDk** [comment]
Hmm. I don't know. I'm fine with either as well 🤷

**Comment by Sjimooon** [comment]
I would prefer if we followed the requiments and linked to different sections with the models to keep the API tables short and concise. The link could just be the endpoint name of the 'API endpoint' column.

**Comment by jeongoks** [comment]
I will make an issue for the remaining two tables and then move this to done. 😊
