### ISSUE TITLE
Tooltips for Admin Portal (Review this later)

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#32]
The tooltips displayed on the Book Web on relevant interactions (see [Req. 2.9](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.be25ggj1naoy) and [req. 7.4](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.1uttnsjpemdi)).

**Comment by ZhakalenDk** [comment]
@jeongoks  How are we looking regarding this?

**Comment by jeongoks** [comment]
I do not see anywhere in the admin portal where this is necessary at the given moment, so therefore i am closing it.
