### ISSUE TITLE
API documentation endpoint

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#37]
Endpoint that gets a page with all API documentation (see [req. 8.3.b](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.lnadeol62wc5)).

**Comment by jeongoks** [comment]
Closed in #33
