### ISSUE TITLE
Create Book Mobile

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#39]

**Comment by ZhakalenDk** [comment]
What's the color pallet we use?
- Primary
- Secondary
- Tertiary

What about Dark Mode?
- Primary
- Secondary
- Tertiary

What about Text color?

Also, complete Black or White is not actually preferable since they're strong in contrast when looking at a screen. Slightly warmer white is better, I think. Normally warmer tones are used when relaxation is the target, which I believe it is for us.

Also do we run with "ALL CAPS" for buttons or "Uppper case" or "lower case".

**Comment by ZhakalenDk** [comment]
![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/d34d0def-c4c1-4033-aa93-eac3930494d8)

**Comment by ZhakalenDk** [comment]
![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/c5bcd857-4597-4240-beb2-9c527bd21fda)

**Comment by ZhakalenDk** [comment]
Although my desigs skills are superb and clearly way better than anyone else in the world, I would like @jeongoks to smash up a design for the app. Can you do that Monday?

I know you're working on the Book Web as well. But being color blind I'm kinda lost here.
I just need a design and I can slap it together like pandcakes and sirup on a fruity summer mornin' at grandma's 🤷

**Comment by ZhakalenDk** [comment]
Font size scaler: https://typescale.com/

**Comment by jeongoks** [comment]
What's the color pallet we use?

- Primary
  - #AF96FF
- Secondary
  - #DFD8F7
- Tertiary
  - #7A59E3

What about Dark Mode?

- Primary
  - #9675FF
- Secondary
  - #DFD8F7
- Tertiary
  - #7A59E3

What about Text color?

- PrimaryDarkText
  - #242424
- SecondaryDarkText
  - #DFD8F7

This is kinda following the purple-ish color theme that we have on both the Book Web and Admin Portal and I am thinking we should continue with that to see that that the Book Web and Mobile is a replicate of one another. I do not know how extensive you wanted the designing to be other than the coloring palette. 😊

I have this already on the branch `jbn/create-mobile-app` where i've also added the tabbar and fontawesome icons:
![image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/61870713/22e1323e-ed77-42d7-b142-24a1c50321a0)
