### ISSUE TITLE
Read/Listen access (Book Mobile)

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#41]
[See Req. 4.9](https://docs.google.com/document/d/1LtJKy3JLAMPYglDSLVlHU5Js0ycNd-HI4G2w6CU5bJ0/edit#bookmark=id.963roe3wcdg1)

**Comment by ZhakalenDk** [comment]
This is connected to #59 and depends on its implementation.

**Comment by ZhakalenDk** [comment]
HOw are we looking on this?
Can I begin the implementation of the ContentView?

**Comment by jeongoks** [comment]
Yes you can, we merged in the `EpubReaderService` earlier today - I added the functionality for the bare minimum of getting the content shown; if any questions or additions is needed, then please let me know.

**Comment by ZhakalenDk** [comment]
Only reading is implemented. Hopefully audio can come along soon
