### ISSUE TITLE
Book Controller

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#44]
- [x] GetBooks `books`
- [x] GetBook `books/{id}`
- [x] AddBook  `books`
- [x] UpdateBook `books/{id}`
- [x] DeleteBook `books/{id}`

**Comment by ZhakalenDk** [comment]
I believe that we have our models within a folder?

`ViewModels/Books/BookModel.cs`
`ViewModels/Books/BookInfo.cs`

And so on? (:

**Comment by ZhakalenDk** [comment]
Do we want Books to be collected without their content?
I'm thinking it's relevant when we only want to display the info of the book.
We do not want to download audio clip of 1-2 hours everytime we want to display a book, right?

Example:
`ViewModels/Books/BookInfo.cs`
`ViewModel/Books/Book.cs`

Book could inherit from `BookInfo` in this case.

**Comment by ZhakalenDk** [comment]
I can't find a difference in the way we create a new `Book` and update and existing one 🤔

**Comment by jeongoks** [comment]
I don't think there's much of a difference... the only property which can't be updated would be the Publisher and Publication year I would think? 🤔

**Comment by ZhakalenDk** [comment]
> I don't think there's much of a difference... the only property which can't be updated would be the Publisher and Publication year I would think? 🤔

Hmm. I don't know. Wouldn't they be updatable as well, though?

**Comment by jeongoks** [comment]
Depends... A book is published when it is... I wouldn't say that the year/date ever changes for that... it's the same as movies; then it would be a whole new book, maybe with another front cover, etc. but the content is the same...

**Comment by ZhakalenDk** [comment]
> Depends... A book is published when it is... I wouldn't say that the year/date ever changes for that... it's the same as movies; then it would be a whole new book, maybe with another front cover, etc. but the content is the same...

No it's more in the sense that they can change the value itself.
Like if they made a mistake 🤔

**Comment by ZhakalenDk** [comment]
I've skipped the update of genres and authors on books for now (Until I find a satisfying way to do it), however, the rest are done.
