### ISSUE TITLE
User Controller

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#45]
- [x] AddUser `users`
- [x] GetUser `users/{id}`
- [x] GetBooks `users/{id}/books`
- [x] UpdateUser `users/{id}`
- [x] DeleteUser `users/{id}`
- [x] SuspendUser `users/{id}/suspend`

**Comment by Sjimooon** [comment]
Currenly, the option of suspending a user is missing from our ER diagram and entities. Should we still add this?
If yes, when, how and why should the `IsSuspended` flag be set?

**Comment by ZhakalenDk** [comment]
> Currenly, the option of suspending a user is missing from our ER diagram and entities. Should we still add this? If yes, when, how and why should the `IsSuspended` flag be set?

Good question 🤔 
Maybe we could just use the soft delete feature to simulate this?
And just "_undelete_" the account if a suspension is lifted? 🤷

**Comment by Sjimooon** [comment]
Maybe. However, I had the impression that a suspended user would still be able to login to download already purchased content - but unable to do anything else within the app(?). Putting a deleted flag on their account would prevent them from doing that. 🤔

**Comment by ZhakalenDk** [comment]
Yea. True 🤔 
Should we ditch the suspension featuere or implement it?

If we implement it we would need to have a flag, I guess.
Or and AccoutStatus field that can hold; Active, Deleted, Suspended?

**Comment by Sjimooon** [comment]
Hmm, we _could_ wait for a bit to get the core parts of the application running first. But for when we would like to implement it; how about if we added another AccountType for a suspended user?

**Comment by ZhakalenDk** [comment]
I think that could work fine, actually.
Especially because we, by doig that, can prohibit access to several things, including subscribtion libraries 👌

**Comment by jeongoks** [comment]
Adding it as another AccountType sounds like a good plan.
