### ISSUE TITLE
Add Sign in attempts and lock-out

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#53]
Currently we don't have that sign in attempts anywhere or how long a user is locked out before they're able to attempt signing in again.

**Comment by ZhakalenDk** [comment]
Is this only for the API Identity setup or also for the clients?

**Comment by jeongoks** [comment]
I am unsure if it needs to be done on clients - i am guessing there needs to be some sort of check on whether they're locked out or not.

**Comment by ZhakalenDk** [comment]
Yea. The API should report back that access was denied. Too many tries.
