### ISSUE TITLE
Setup constraints in EF Core

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#54]
Constrains proposal:
`Account`
- `Email` (Max length: 256, indexed and unique)
- `NormalizedEmail` (same as `Email`)
- `Username` (Max length: 128)
- `NormalizedUserName` (same as `Username`)
- Excluded from queries when `IsDeleted == true` unless explicitly told not to.

`AccountType`
- `Name` (Max length: 128)

`AccessType`
- `Name` (Max length: 128)

`Author`
- `Name` (Max length: 128)

`Book`
- `Title` (Max length: 256)

`ContentType`
- `Name` (Max length: 128)

`Genre`
- `Name` (Max length: 128)

`Operator`
- `Name` (Max length: 128)
- `Surname` (Max length: 128)

`Publisher`
- `Name` (Max length: 128)

`User`
- `Name` (Max length: 128)
- `Surname` (Max length: 128)

Additionally `Guid` IDs will be used instead of `int` IDs for all entities (see issue #55).

_The assignee will correct the requirments in the Project Report_

**Comment by ZhakalenDk** [comment]
Remember to check if [Seeding](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/tree/developer/PubHub/PubHub.API/Domain/Seeding) is still working as intended after this chance.

**Comment by ZhakalenDk** [comment]
Remember cascading contraints where relevant
