### ISSUE TITLE
Fix ER-Diagram & Data model in draw.io

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#55]
Link is [here](https://viewer.diagrams.net/?page-id=OK300gTmYLWmXQ7AiAHA&highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=OK300gTmYLWmXQ7AiAHA#G1AstL6DjKUFWGjdMqgRx2_xQavsjabBYW).

**Comment by ZhakalenDk** [comment]
![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/27011156/e1d6136e-b924-4600-a2ac-856c64bf0b9f)

**Comment by ZhakalenDk** [comment]
Burde vi have et `Guid` der bruges som display ID i stedet for `int`.

Det giver mere mening når vi skal vise det for brugeren i form af URL pathing.
Security-wise giver det mere mening at have et unpredictable i stedet for et predictable ID.

`book/dfghy-1dfg2-6fasd/view` vs. `book/1/view`.

Med andre ord: Du kan prøve at skrive `book/2/view` og se hvad der sker. Det ville muligvis give adgang til noget man ikke burde have adgang til 🤷
