### ISSUE TITLE
Seeding data

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#58]
- Everything for a book
   - Content might be difficult to do for now 
 - 1-2 publishers
 - 1 operator
 - 1 user
 - Access types
   - Owner
   - Subscriber
   - Null (if a user unsubscribes) Access type should be nullable

**Comment by jeongoks** [comment]
Need to be done by Thursday pls :) (ignore)

**Comment by ZhakalenDk** [comment]
> Need to be done by Thursday pls :) (ignore)

You got it :D

**Comment by ZhakalenDk** [comment]
Are we going to store area codes for phone numbers? 🤔 

`87654321` vs `45876543321`.

I think it's relevant as the company already expects global integration? 🤷
