### ISSUE TITLE
Figure out Book content

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#59]
We need to figure out how the content for an audio book and an ebook works in the DB and how we should handle that data. @jeongoks can provide an audio book file and can also get an ebook file.

- [x] Handle larger files ( see #144 )
- [x] Made the Book content endpoint ( see #177 )
- [x] Make the Book content serivce

**Comment by ZhakalenDk** [comment]
@jeongoks Mentioned that she has some way of dealing with this.

I think it's only relevant when our front has the capability to handle it

**Comment by jeongoks** [comment]
I think we should prioritize figuring this out when the auth is in place.

**Comment by ZhakalenDk** [comment]
See also #144 as that is strongly connected to this problem set

**Comment by ZhakalenDk** [comment]
DO we only need ot figure out how to do Audio now?

**Comment by jeongoks** [comment]
Depends if the e-book content works immediately? I will test tomorrow whether or not we can handle larger files after @Sjimooon PR earlier today, where he added a `timeout` to the client in case of bigger uploads.

However, I do not think we have time to optimize the way we store the content, so we need to make sure we write that we wish to store it differently but, for the sake of the prototype and time limit, we figured this out too late to change.

I don't know how easy it'd be to implement audio functionality if the handling of bigger files works. @Sjimooon mentioned that the SQL server will get slow if we have a lot of requests uploading the bigger files as it is right now. 🤔

First priority would be to make sure the .epub files can be read properly in the book mobile.

And then if that gets done, maybe we can have a talk about if we should attempt to get the audio working.
