### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#61]
Do validation of user data (i.e. data sent to update (PUT) endpoints).
Ideally, I see the same logic used on both the frontend and backend with [FluentValidation](https://docs.fluentvalidation.net/en/latest/aspnet.html). This means, it would live together with the data models present in the shared `PubHub.Common` assembly and be used twice; once on the client (for user feedback) and then once again on the server (to ensure data integrity). Using the same validation rules allows for simplicity and consistency, contributing to easier maintenance and an implementation that is more easily kept secure against malformed data submission and potential threats.

I have already written custom components and helpers for property accessor parsing to make FluentValidation compatible with Blazor (only tested on Blazor Server though...). I don't know about MAUI.

**Comment by ZhakalenDk** [comment]
Interesting. I agree. Let's try it out.

Also. Does this mean that we want to share View Models across assemblies?
Or do we want replicas in each executable?

**Comment by Sjimooon** [comment]
Yeah, I might have been a little early on the `PubHub.Common` stuff. 😅
In commit 61c14b2 i added the assembly with a `Models` namespace. I though these could be shared between the API and the client applications making both sides agree to use the same classes (same excact structure and easy to maintain) to serialize and then de-serialize by the other.

They are our DTO's in a sense, but they could also be used as the _models_ in FluentValidation. (In FluentValidation you create a validator from a generic class where the generic type you use, is the the model that is to be validated.)

**Comment by ZhakalenDk** [comment]
It's fine but I feel like we need to discuss these kinda things before we make the choice by ourself as it affects the entire structure of the repository and what I've created (_Based on the feedback I got in issue #44_) is now to be moved out and into another assembly that I don't have on my branch 🤷
