### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#68]
Currently VS doesn't agree with our prefered way of naming constants (which is SCREAMING_SNAKE_CASE) . We should add an `.editorconfig` file to avoid accedentially following VS's guidance and clarify this in our project report.

![Image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/122673993/7ea8e544-5476-4f10-a89b-3c7d9862cb3a)

VS wants to do `_invalidId` for private constants.

**Comment by ZhakalenDk** [comment]
It actually just wants you to add the '_' prefix, however, I agree. We should specify our ruleset in a .editorconfig

**Comment by Sjimooon** [comment]
Oh, sorry. It seems that way from the screen snip - but it just gets greedy when you start lisening 😅: 
![image](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/assets/122673993/951f337c-0799-47ee-be55-e116f7b8c29e)

**Comment by ZhakalenDk** [comment]
WTH... I guess we have to slap it around a bit 😆

**Comment by ZhakalenDk** [comment]
Make is so that primary constructor is not the prefered way.

**Comment by Sjimooon** [comment]
This was fixed with PR #87.
