### ISSUE TITLE
Endpoint services

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#76]
- [x] BookService
- [x] UserService
- [x] PublisherService
- [ ] AuthenticationService

**Comment by ZhakalenDk** [comment]
I think this should be closed and then move the task for Authentication Services into a new issue.

**Comment by jeongoks** [comment]
> I think this should be closed and then move the task for Authentication Services into a new issue.

I will do that 🫡

**Comment by jeongoks** [comment]
AuthenticationService is moved to a seperate issue #92
