### ISSUE TITLE
Make Problem Specifications comply with RFC9457

### ISSUE THREAD

**Issue by ZhakalenDk** [Mike-Mortensen-Portfolio/PubHub_H6_Final#84]
The current specifications, while complying, does not directly follow the standard as they need a URI, among other stuff. See [Defining New Problem Types](https://www.rfc-editor.org/rfc/rfc9457.html#name-defining-new-problem-types)

**Comment by jeongoks** [comment]
Was [this](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Documentation) what you were after @ZhakalenDk ?

**Comment by ZhakalenDk** [comment]
> Was [this](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Documentation) what you were after @ZhakalenDk ?

Almost 😃

**Comment by jeongoks** [comment]
Does [this](https://github.com/Mike-Mortensen-Portfolio/PubHub_H6_Final/wiki/Api-Documentation#duplicate-problem-specification) satisfy it better or is the description too complex still? 🤔

**Comment by ZhakalenDk** [comment]
>If you recieved this repsonse is means that the attempt to persist an entity yielded a conflict - this specific conflict represents a >duplication error and essentially means that the entity already exists.
>
>Make sure to only push data for creation that is **not** already persisted. If you intended to update an entity use [INSERT >ENDPOINT]().
How does this sound?

**Comment by jeongoks** [comment]
I tweaked it a bit as there will be multiple update endpoints - so I am guessing we want it to be generalized?

**Comment by ZhakalenDk** [comment]
I'm gonna add the necessary code changes then.
