### ISSUE TITLE
Create API unit test project

### ISSUE THREAD

**Issue by Sjimooon** [Mike-Mortensen-Portfolio/PubHub_H6_Final#91]
Create a new project for unit tests called `PubHub.API.UT` under a new '/test/' directory.

To start out, prepare a single testing one of the API endpoints with a database fixture (and maybe moq too).

**Comment by jeongoks** [comment]
I think we need to be a bit wary of using moq - or at least use the version where they don't have SponsorLink included

I do not know if that's an issue for this prototype version but, I do think we should take it into consideration.

[This article](https://steven-giesel.com/blogPost/1939d20c-2493-4bf7-9636-96436283fb72) also mentions something about GDPR compliance issues with this.

**Comment by ZhakalenDk** [comment]
Can we call the namespace `.Tests` instead of `.UT`? 🤔 
Not that it matters much, I just feel like it defines the project more.

> I think we need to be a bit wary of using moq - or at least use the version where they don't have SponsorLink included
> 
> I do not know if that's an issue for this prototype version but, I do think we should take it into consideration.
> 
> [This article](https://steven-giesel.com/blogPost/1939d20c-2493-4bf7-9636-96436283fb72) also mentions something about GDPR compliance issues with this.

I feel like this is defo somehting we should consider 🤔

**Comment by Sjimooon** [comment]
> Can we call the namespace `.Tests` instead of `.UT`? 🤔 Not that it matters much, I just feel like it defines the project more.
> 
> > I think we need to be a bit wary of using moq - or at least use the version where they don't have SponsorLink included
> > I do not know if that's an issue for this prototype version but, I do think we should take it into consideration.
> > [This article](https://steven-giesel.com/blogPost/1939d20c-2493-4bf7-9636-96436283fb72) also mentions something about GDPR compliance issues with this.
> 
> I feel like this is defo somehting we should consider 🤔

If we are to create more types of test than just unit test (which are supposed to be run during CI build jobs), I think we should have a naming scheme to differentiate between the different types. I propose: UT (Unit Test),  IT (Integrations Test) and FT (Function Test). Our performance tests on a system in a staging environment would fall under the later.

**Comment by ZhakalenDk** [comment]
I gotta be honest I'm not familiar with any of this.
We rarely do Unit Tests at my company. In fact I haven't created one since School 😆

**Comment by jeongoks** [comment]
I think it's best to keep it minimum, so maybe for now just get the unit tests up as we know them and then if there's time we can integrate more of them?

**Comment by ZhakalenDk** [comment]
Integrate more of what? 🤔

**Comment by jeongoks** [comment]
The IT and FT - I don't know if they're any different though, from unit tests. So it was more if they were different from the Unit tests 😂
