### ISSUE TITLE
AuthenticationService needs to be implemented

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#92]

**Comment by jeongoks** [comment]
I am guessing this service might need to be done a bit differently now with the `AuthencationController` or should it be doing the same as the other ones? 🤔 I am in a bit of doubt with this.

**Comment by ZhakalenDk** [comment]
Depends. What's it doing now that you feel is different?

**Comment by jeongoks** [comment]
I guess I am just unsure about how to really implement everything with the authentication right now. 🤔

**Comment by ZhakalenDk** [comment]
You don't have to do much.
The service should just call the endpoints (:
Maybe do some validation before sending a request.

Like make sure that the user provided a password and a username (email) and so on.
However, the endpoints are doing the magic for you regarding authentication.

You will, although, have to set up the client to make use of the tokens .

**Comment by jeongoks** [comment]
Okay. I will try to look into it but, this might take me some time.

Should it be divided into 2 issues... this being 1 and then 1 with the client?

**Comment by ZhakalenDk** [comment]
Yes. This is the service implementation.
The other is client compliance (:

**Comment by jeongoks** [comment]
In none of our models handling creation of `Publisher` or a `User` or the `Account` have any logic for a password... is this intentionel? Or is this just missing because we haven't talked about how we handle those... or am I just not observationsal enough. 😅

**Comment by ZhakalenDk** [comment]
As far as I can see there's not logic to actually register new users
