### ISSUE TITLE
Using Radzen or MudBlazor for some UI elements

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#95]
When we need to make multiselection dropdowns and do that statistics page for the Publishers, I suggest that we're using either Radzen or MudBlazor for those elements. For simplicity and also to give the users a good experience, rather than maybe ending up with a wonky chart that we've made ourselves.

I can also try to reaserch for certain NuGet packages only doing those specific things, as we'd have to add the entirety of MudBlazor components and Radzen components, despite us maybe only using few elements.

So I'd like you guys' feedback on this as soon as possible, so that I can look into other solutions if you're against adding huge UI third-party libraries and would rather specific NuGet for the specific purpose. 😊

**Comment by ZhakalenDk** [comment]
What's the difference between the two?
Why select one over the other?

**Comment by jeongoks** [comment]
They're doing basically the same, they're two big Blazor UI NuGet packages with a lot of UI components there makes handling HTML/CSS/JS much easier through already finished libraries.

They do the same so, I wouldn't say to choose one over the other is better... I think it's a better question which style you like the most of the components that they offer tbh.

If we need a Rich text editor, however, only Radzen offers that but, I don't see any usage of that in this prototype when we don't implement the editing of the front page.

**Comment by ZhakalenDk** [comment]
Might wont to give publishers rich text capabilities when writing descriptions for their books ? 🤔
Can you private demonstration on the two styles, so we can look at it and make a choice based on that?

**Comment by jeongoks** [comment]
I can link their two documentations or show those when we have the meeting today - I think it'd be a waste of time to set up different demonstrations on the two; So I will show on their documentation examples.

Also, Publishers won't give a description to the books currently - so I don't know if we want to add that and maybe call it summary instead of description? And even then, I wouldn't say that there's needed bold, italic, underline or lists. However, we can talk about that as well. 😊

**Comment by jeongoks** [comment]
We've agreed to use one of the bigger libraries for the elements that needs a little more than some simple bootstrap to make the functionality work more smoothly.
