### ISSUE TITLE
GenreController endpoint

### ISSUE THREAD

**Issue by jeongoks** [Mike-Mortensen-Portfolio/PubHub_H6_Final#99]
- [x] GetGenres `GET/genres`
- [x] GetGenre `GET/genres/{id}`

**Comment by ZhakalenDk** [comment]
I'll create `Add` and `Delete` endpoints as well.
Although now that I think about it. Why would we ever delete a genre?

**Comment by jeongoks** [comment]
I don't think that Delete is necessary... `Add` makes sense I guess? You guys just told me that it'd be created automatically in the `AddBook` ?

**Comment by ZhakalenDk** [comment]
I've created them both. If they're not used we can remove them
